### ISSUE TITLE
Suggestion for improvement to employee_review.md

### ISSUE THREAD

**Issue by escattone** [mozmeao/peer-review#1]
I would suggest making an adjustment to point #5 of the [`employee_review.md`](https://github.com/mozmeao/peer-review/blob/master/employee_review.md), specifically this part:

> focus and spend the most amount of time on the items that are hard or uncomfortable to discuss, usually that's where the value is.

In my experience of this, it can feel like the message is "you're not a valued member of the team for these reasons" rather than "you're a valued member of the team, and here's one or two ways you can improve". I think it's very important to spend enough time on the positive feedback so that the "you're a valued member of the team" part feels believable, and the subsequent focus on the hard things doesn't feel like an existential threat.

**Comment by bensternthal** [comment]
@escattone can you suggest a re-wording that captures your points?

**Comment by escattone** [comment]
@bensternthal I kept writing and re-writing point #5 and finally settled on the following. How does it sound to you?

> Make sure to cover the themes that developed, spend enough time on the positive feedback to ensure that when focusing on the items that are hard or uncomfortable, they are taken in context.

**Comment by bensternthal** [comment]
Updated! Much thanks. Let me know if you see any additional tweaks or changes.
